MyProject_Sua lai Navbar/MyProject/mysite/mysite/urls.py
from django.contrib import admin

from django.contrib.auth import views as auth_views

from django.conf.urls import include, url

from polls.urls import poll_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url('r^poll/',include(('polls.urls',poll_urlpatterns), namespace='poll',app_name = 'polls'))
    #include(module, namespace=None, app_name=None)
    url(r'^janonymous/', include(poll_urlpatterns)),

]

MyProject_Sua lai Navbar/MyProject/mysite/polls/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
app_name = "polls"
poll_urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^signup/$', views.Signup, name='Signup'),
    url(r'^login/$', views.login_user, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^home/$', views.home, name='home'),
    url(r'^about/$', views.AboutPage_django, name='about'),
    url(r'^dialog/$', views.Dialog, name='dialog'),
    url(r'^MVC/$', views.MVC, name='MVC'),
    url(r'^structure/$', views.structure, name='structure'),
    url(r'^website/$', views.website, name='website'),
    url(r'^databasesupport/$', views.databasesupport, name='databasesupport'),
    url(r'^alphabet/$', views.alphabet, name='alphabet'),
    url(r'^compare/$', views.compare, name='compare'),
    url(r'^hiragana/$', views.hiragana, name='hiragana'),
    url(r'^katakana/$', views.katakana, name='katakana'),
    url(r'^vocabulary/$', views.vindex, name='show'),
    url(r'^vocabulary/(?P<set_id>[0-9]+)(:show)?/?$', views.show_set, name='show'),
    url(r'^vocabulary/(?P<set_id>[0-9]+)/flip/?$', views.flip, name='flip'),
    url(r'^vocabulary/(?P<set_id>[0-9]+)/learn/?$', views.learn, name='learn'),
]

MyProject_Sua lai Navbar/MyProject/mysite/polls/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class Lesson (models.Model):
    name = models.CharField(max_length= 256)
    def __str__(self):
        return self.name
class Card (models.Model):
    Lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    front_jap = models.CharField(max_length= 256)
    back_eng = models.CharField(max_length=256, default= 'Null')
   # audio = models.FileField(upload_to='./static/polls/audio', default= 'mơ/mysite/polls/static/polls/audio/Death1.wav')
    def __str__(self):
        return self.front_jap+", "+self.back_eng


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text



class Video(models.Model):
    title = models.CharField(max_length=300)
    link = models.CharField(max_length=300)
    time = models.DateTimeField()
    def __str__(self):
        return self.title

MyProject_Sua lai Navbar/MyProject/mysite/polls/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from .models import Lesson,Card


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']
class LoginForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','password')

class LessonForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput, label='')
    color = forms.CharField(widget=forms.TextInput, label='')

    class Meta:
        model = Lesson
        fields = ['name']


class CardForm(forms.ModelForm):
    front = forms.CharField(widget=forms.TextInput, label='')
    back = forms.CharField(widget=forms.TextInput, label='')

    class Meta:
        model = Card
        fields = ['front', 'back']

MyProject_Sua lai Navbar/MyProject/mysite/polls/views.py
from random import randrange

from django.core import serializers
from django.forms import formset_factory
from django.shortcuts import render

from django.shortcuts import redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm
# from django.http import HttpResponse
from django.http import HttpResponseRedirect
# Create your views here.
from django.http import HttpResponse
# from .forms import UserForm, LoginForm
from .forms import UserForm, CardForm, LessonForm
from .models import Video, Lesson, Card

all_sets = {}
current_cards = {}
current_set_id = -1
empty_card_index = 0
admin = False


# Showing the vocabulary page
def vindex(request):
    global all_sets
    all_sets = Lesson.objects.all()
    set_lens = []
    for set in all_sets:
        # Subtract one from the length for the empty card.
        set_lens.append(len(set.card_set.all()) - 1)

    return render(request, 'Flashcards\index.html', {'all_sets': all_sets, 'set_lens': set_lens, 'admin': admin})


def show_set(request, set_id):
    global all_sets, current_cards, current_set_id
    lesson = Lesson.objects.get(id=set_id)
    current_cards = lesson.card_set.all()
    # current_cards = Card.objects.all()
    title = lesson.name
    current_set_id = set_id

    return render(request, 'Flashcards\set.html', {
        'set_id': set_id, 'cards': current_cards, 'title': title, 'empty_card_index': 0, 'admin': admin
    })


def flip(request, set_id):
    flashcards = serializers.serialize("json", Lesson.objects.get(id=set_id).card_set.all())
    return render(request, 'Flashcards/flip.html', {
        'cards': flashcards, 'set_id': set_id, 'admin': admin
    })


def learn(request, set_id):
    flashcards_data = Lesson.objects.get(id=set_id)
    flashcards = serializers.serialize("json", flashcards_data.card_set.all())
    return render(request, 'Flashcards/learn.html', {
        'title': flashcards_data.name, 'cards': flashcards, 'set_id': set_id, 'admin': admin
    })


def index(request):
    query = request.GET.get("q")
    if query:

        return render(request, 'Login/base_visitor.html')
    else:
        return render(request, 'Login/base_visitor.html')


def Signup(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'home/home.html')
    context = {
        "form": form,
    }
    return render(request, 'Login/register.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'Q&A/home.html')
            else:
                return render(request, 'Login/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'Login/login.html', {'error_message': 'Invalid login'})
    return render(request, 'Login/login.html')


def logout(request):
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, "Login/login.html", context)

# def test(request):
#     return render(request, 'test.html')

def home(request):
    return render(request, 'home/home.html')


def AboutPage_django(request):
    return render(request, 'home/about.html')


def Dialog(request):
    list_video = Video.objects.all()
    context = {'list_video': list_video}
    return render(request, 'Japanese/dialog.html', context)


def MVC(request):
    return render(request, 'Q&A/MVC.html')


def structure(request):
    return render(request, 'Q&A/structure.html')


def website(request):
    return render(request, 'Q&A/website.html')


def databasesupport(request):
    return render(request, 'Q&A/databasesupport.html')


def alphabet(request):
    return render(request, 'Japanese/alphabet.html')


def compare(request):
    return render(request, 'Q&A/compare.html')


def hiragana(request):
    return render(request, 'Japanese/hiragana.html')


def katakana(request):
    return render(request, 'Japanese/katakana.html')

MyProject_Sua lai Navbar/MyProject/mysite/polls/templates/Flashcards/flip.html
{%  extends 'home/basepage.html' %}
{% load staticfiles %}

{% block body %}
    <style>
        .front {
            position: static;
        }

    .navigation.row {
        margin-top: 1%;
    }

    </style>

    <div class="container">
       <div id="set-title">

            <span id="id_name">{{ title }}</span>
            <svg width="28" height="28" style="vertical-align: bottom;">

            </svg>
            <input id="learn-btn" class="btn btn-default btn-md" value="Learn"  style="background-color:darkorange"
                   onclick="window.location.href='{% url 'learn' set_id %}'" />
            <input id="flip-btn" class="btn btn-default btn-md" value="View" style="background-color: plum;"
                   onclick="window.location.href='{% url 'show' set_id %}'" />
        </div>
    </div>
    <div class="container-fluid">
        <div class="card row">
            <div class="col-xs-offset-2 col-sm-offset-2 col-md-offset-2 col-lg-offset-2
                        col-xs-8 col-sm-8 col-md-8 col-lg-8 card-container">
                <div id="card">

                  <div class="card-side front text-center">
                    <span id="front-content"></span>
                  </div>
                  <div class="card-side back text-center">
                      <span id="back-content"></span>

                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="navigation row">

            <div class="col-xs-offset-3 col-sm-offset-3 col-md-offset-3 col-lg-offset-3
                        col-xs-2 col-sm-2 col-md-2 col-lg-2 card-container">
                <div id="left-card">
                  <div class="turn-btn text-center" onclick="prevFlip()">
                      prev
                  </div>
                </div>
            </div>


            <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2 card-container">
                <div id="card-index" class="text-center">
                </div>
            </div>


            <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2 card-container">
                <div id="right-card">
                  <div class="turn-btn text-center" onclick="nextFlip()">
                      next
                  </div>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'flashcard/js/flip.js' %}"></script>
    <script>
        window.onload=function() { playFlip({{ cards|safe }}); };

        $(document).ready(function() {
            $(".card-side.front").css('position', 'absolute');
            $(".card-side.back").css('position', 'static');
        });
    </script>
    </div>
{% endblock %}

MyProject_Sua lai Navbar/MyProject/mysite/polls/templates/Flashcards/index.html
{%  extends 'home/basepage.html' %}
{% load flashcard_extras %}

{% block body %}
      <div id="set-title" style="color:black" >
          <center><span id="id_name">Lesson </span></center>
      </div>
    <div class="container-fluid">

         {% for set in all_sets %}

            <div class="col-sm-12 col-md-6 col-lg-3 card" onclick="location.href='/janonymous/vocabulary/{{ set.id }}/flip';">
                <div>
                  <div class="third front text-center" style="background-color:lightyellow">
                      <a id="front-content">{{ set.name }}</a>
                  </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

MyProject_Sua lai Navbar/MyProject/mysite/polls/templates/Flashcards/learn.html
{%  extends 'home/basepage.html' %}
{% load staticfiles %}

{% block body %}
    <style>
        #word-container, #answer-input {
            font-size: 24px;
        }
        #answer-btn {
            display: inline;
            font-size: 20px;
        }
        #learn-container, #score-container, #result-container, #end-container {
            border-style: solid;
            padding: 1%;
            border-width: 1px;
        }
        #learn-container {
            margin-right: 1%;
        }
        .score-info {
            font-weight: bold;
        }
        #correct-count {
            color: green;
        }
        #incorrect-count {
            color: red;
        }

    </style>
    <div class="container">
         <div id="set-title">
            <span id="id_name">Learn {{ title }}</span>

            <input id="learn-btn" class="btn btn-default btn-md" value="View" style="background-color: plum;"
                   onclick="window.location.href='{% url 'show' set_id %}'" >
            <input id="flip-btn" class="btn btn-default btn-md" value="Flip" style="background-color: yellowgreen"
                   onclick="window.location.href='{% url 'flip' set_id %}'" >
        </div>
    </div>
    <div class="container">
        <div id="learn-container" class="container col-xs-8 col-sm-8 col-md-8 col-lg-8">
            <div id="word-container">
            </div>
            <div>
                <input id="answer-input">
                <a id="answer-btn" class="btn btn-default" style="background-color:lightskyblue"   onclick="answerLearn()">Answer </a>
            </div>
        </div>
        <div id="result-container" class="container col-xs-8 col-sm-8 col-md-8 col-lg-8" style="display: none">
            <div id="result" class=" text-center">
                RESULT
            </div>
            <div id="question" class="container">
                Q:
            </div>
            <div id="correct-answer" class="container">
                A:
            </div>
            <span id="next-container">
            </span>
        </div>
        <div id="score-container" class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
            <p class="score-info">Remaining</p>
            <p id="remaining-count"></p>
            <p class="score-info">Correct</p>
            <p id="correct-count"></p>
            <p class="score-info">Incorrect</p>
            <p id="incorrect-count"></p>
        </div>
        <div id="end-container" class="container col-xs-8 col-sm-8 col-md-8 col-lg-8" style="display: none;">
            <p id="correct-count-end">Correct: </p>
            <p id="incorrect-count-end">Incorrect: </p>
            <p id="info-end"></p>
            <span id="next-container-end"></span>
        </div>
    </div>

    <script src="{% static 'flashcard/js/learn.js' %}"></script>
    <script>
        window.onload=function() { playLearn({{ cards|safe }})};
    </script>
{% endblock %}

MyProject_Sua lai Navbar/MyProject/mysite/polls/templates/Flashcards/set.html
{%  extends 'home/basepage.html' %}

{% block body %}

    <div class="container">
          <div id="set-title">

            <span id="id_name">{{ title }}</span>
            <svg width="28" height="28" style="vertical-align: bottom;">

            </svg>
            <input id="learn-btn" class="btn btn-default btn-md" value="Learn" style="background-color:darkorange"
                   onclick="window.location.href='{% url 'learn' set_id %}'" />
            <input id="flip-btn" class="btn btn-default btn-md"  value="Flip" style="background-color: yellowgreen"
                   onclick="window.location.href='{% url 'flip' set_id %}'" />
        </div>
        <table id="set-list" class="table">
            <thead id="card-cols">
                <th></th>
                <th>Terms</th>
                <th>Definitions</th>
               <th></th>
            </thead>
            <tbody>
                {% for card in cards %}
                    <tr id="card-{{ forloop.counter0 }}" class="card">
                        <td class="counter">{{ forloop.counter0 }}</td>
                        <td class="card-front">{{ card.front_jap }}</td>
                        <td class="card-back">{{ card.back_eng }}</td>
                        <td></td>
                    </tr>
                {% endfor %}
                <script>window.onload=function() { setEmptyCard({{ empty_card_index}}); }</script>
            </tbody>
        </table>
    {% if admin == True %}

    {% endif %}
    </div>


{% endblock %}

MyProject_Sua lai Navbar/MyProject/mysite/polls/templates/Japanese/alphabet.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load staticfiles %}
  <!-- Theme Made By www.w3schools.com - No Copyright -->
  <title>Study Jananese In Jannonymous</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
  body {
      font: 20px Montserrat, sans-serif;
      line-height: 1.8;
  }

  .bg-2 {
      background-color: #BFCAE6; /* White */
      color: #976D00;
  }
  .bg-4 {
      background-color: #EEE8AA;
      color: #1C1C1C;
  }
  .container-fluid {
      padding-top: 30px;
      padding-bottom: 30px;
  }
  .navbar {
      padding-top: 10px;
      padding-bottom: 1px;
      margin-bottom: 0;
      font-size: 16px;
      letter-spacing: 5px;
  }
  h1 {
  letter-spacing: 5px;
  color: #98FB98;
  font-family: Impact;
  font-size: 60px;
  border: 20px solid transparent;
  padding: 15px;
  border-image: url({%static 'border.png' %}) 10% round;
  border-image-width: 20px;
  text-shadow: 2px 5px #FF0000;
}
  </style>
</head>
<body>


<!-- Navbar -->
<nav class="navbar navbar-inverse" >
  <div class="container-fluid">
    <div class="navbar-header">
      <img src="{%static 'logo.png' %}" class="img-responsive margin" style="width:100%" alt="ImageLogo">
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="../home">HOME</a></li>
        <li><a href="#">VOCABULARY</a></li>
        <li><a href="#">ALPHABET</a></li>
        <li><a href="#">GRAMMAR</a></li>
        <li><a href="#">DIALOG</a></li>
        <li><a href="../about/">ABOUT</a></li><li><a href="#">LOGOUT</a></li>
      </ul>
    </div>
  </div>
</nav>


<!-- Third Container (Grid) -->
<div class="container-fluid bg-2 text-center">
    <div class="row">
      <div class="col-sm-3"></div>
      <div class="col-sm-6"><h1 class="margin"><strong>- JANONYMOUS -</strong></h1></div>
      <div class="col-sm-3 "></div>
    </div>
  <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-4">
      <a href="../hiragana/" class="btn btn-primary btn-lg" role="button">BẢNG CHỮ CÁI HIRAGANA</a>
      <img src="{%static 'hiragana.png' %}" class="img-thumbnail" style="width:100%" alt="ImageHira">
    </div>
    <div class="col-sm-4">
      <a href="../katakana/" class="btn btn-success btn-lg" role="button">BẢNG CHỮ CÁI KATAKANA</a>
      <img src="{%static 'katakana.png' %}" class="img-thumbnail" style="width:100%" alt="ImageKata">
    </div>
    <div class="col-sm-2"></div>

  </div>
</div>


<!-- Footer -->
<footer class="container-fluid bg-4 text-center">
   <p>Fujinet JSC</p>
   <p>Website: <a href="https://www.fujinet.net/">https://www.fujinet.net/</a></p>
   <p>Số điện thoại: 028 3847 7000</p>
</footer>


</body>
</html>

MyProject_Sua lai Navbar/MyProject/mysite/polls/templates/Japanese/dialog.html
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Theme Made By www.w3schools.com - No Copyright -->
  <title>Study Jananese In Jannonymous</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style>
  body {
      font: 20px Montserrat, sans-serif;
      line-height: 1.8;
      color: #f5f6f7;
  }
  p {font-size: 16px;}
  .margin {margin-bottom: 54px;}

  .bg-1 {
      background-color: #474e5d; /* Dark Blue */
      color: #ffffff;
  }
  .bg-2 {
      background-color: #ffffff; /* White */
      color: #555555;
  }
  .bg-3 {
      background-color: #2f2f2f; /* Black Gray */
      color: #fff;
  }
  .container-fluid {
      padding-top: 50px;
      padding-bottom: 50px;
  }
  .navbar {
      padding-top: 15px;
      padding-bottom: 15px;
      border: 0;
      border-radius: 0;
      margin-bottom: 0;
      font-size: 12px;
      letter-spacing: 5px;
  }
  .navbar-nav  li a:hover {
      color: #1abc9c !important;
  }

   .a {
    }
    .a :hover {opacity: 1}

  </style>
</head>
<body>

<!-- First Container -->
<div class="container-fluid bg-1 text-center">
  <center><p>Practice make prefect ...</p></center>
</div>


<!-- Navbar -->
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
         <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="http://localhost:8000/janonymous/home/">HOME</a></li>
        <li><a href="#">VOCABULARY</a></li>
        <li><a href="http://localhost:8000/janonymous/alphabet/">ALPHABET</a></li>
        <li><a href="#">GRAMMAR</a></li>
        <li><a href="http://localhost:8000/janonymous/dialog/">DIALOG</a></li>
        <li><a href="http://localhost:8000/janonymous/about/">ABOUT</a></li>
         <li><a href="http://localhost:8000/janonymous/logout/">LOGOUT</a></li>
      </ul>
    </div>
  </div>
</nav>

<!-- Third Container (Grid) -->
<div class="container-fluid bg-2 text-center">
  <h1 class="margin"><strong>--JANONYMOUS--</strong></h1>
  <div class="row">
      <div class="col-sm-3" >

      </div>
      <div class="col-sm-6">
          <h2> Danh sách Dialog</h2>
          <ul class="list-group">
              {% if list_video %}
              {% for video in list_video %}
              <li id = {{video.id}} class="list-group-item"><a href = "#"> {{video.title}} </a></li>
              {% endfor %}
              {% else %}
              <p>No video</p>
              {%endif%}
          </ul>
      </div>
      <div class="col-sm-3">
      </div>
  </div>
</div>

<!-- Footer -->
<footer class="container-fluid bg-3 text-center">
   <p>Fujinet JSC</p>
   <p>Website: <a href="https://www.fujinet.net/">https://www.fujinet.net/</a></p>
   <p>Số điện thoại: 028 3847 7000</p>
</footer>

</body>
</html>

MyProject_Sua lai Navbar/MyProject/mysite/polls/templates/Login/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Course{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="http://localhost:8000/janonymous/home/">Course</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="http://localhost:8000/janonymous/signup/">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="http://localhost:8000/janonymous/login/">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

MyProject_Sua lai Navbar/MyProject/mysite/polls/templates/Login/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

MyProject_Sua lai Navbar/MyProject/mysite/polls/templates/Login/login.html
{% extends 'Login/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <form class="form-horizontal" role="form" action="{% url 'login'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="../signup">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

MyProject_Sua lai Navbar/MyProject/mysite/polls/templates/Login/register.html
{% extends 'Login/base_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<center>
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'pages/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="../login/">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>
</center>
{% endblock %}